import { z } from "zod";

export const categories = [
  "Animales",
  "Películas",
  "Objetos",
  "Deportes",
  "Comida",
  "Tecnología",
  "General",
] as const;

export type Category = (typeof categories)[number];

export interface WordPair {
  palabra: string;
  pista: string;
}

export const categoryWords: Record<Category, WordPair[]> = {
  Animales: [
    { palabra: "Perro", pista: "Hachiko" },
    { palabra: "Gato", pista: "Nueve vidas" },
    { palabra: "Caballo", pista: "Troya" },
    { palabra: "Pez", pista: "Memoria corta" },
    { palabra: "Pájaro", pista: "Madruga" },
    { palabra: "León", pista: "Simba" },
    { palabra: "Elefante", pista: "Nunca olvida" },
    { palabra: "Serpiente", pista: "Edén" },
    { palabra: "Tortuga", pista: "Liebre" },
    { palabra: "Rana", pista: "Príncipe" },
    { palabra: "Mariposa", pista: "Efecto" },
    { palabra: "Abeja", pista: "Maya" },
    { palabra: "Hormiga", pista: "Cigarra" },
    { palabra: "Araña", pista: "Peter Parker" },
    { palabra: "Tiburón", pista: "Spielberg" },
    { palabra: "Delfín", pista: "Flipper" },
    { palabra: "Ballena", pista: "Moby Dick" },
    { palabra: "Pulpo", pista: "Paul" },
    { palabra: "Cangrejo", pista: "Lateral" },
    { palabra: "Águila", pista: "Calva" },
    { palabra: "Búho", pista: "Lechuzas" },
    { palabra: "Pingüino", pista: "Esmoquin" },
    { palabra: "Oso", pista: "Yogui" },
    { palabra: "Lobo", pista: "Aullar luna" },
    { palabra: "Zorro", pista: "What does say" },
    { palabra: "Ciervo", pista: "Bambi" },
    { palabra: "Conejo", pista: "Pascua" },
    { palabra: "Ratón", pista: "Mickey" },
    { palabra: "Murciélago", pista: "Bruce Wayne" },
    { palabra: "Cebra", pista: "Paso" },
    { palabra: "Jirafa", pista: "Melman" },
    { palabra: "Hipopótamo", pista: "Gloria" },
    { palabra: "Rinoceronte", pista: "Jumanji" },
    { palabra: "Gorila", pista: "King Kong" },
    { palabra: "Mono", pista: "Darwin" },
    { palabra: "Koala", pista: "Australia" },
    { palabra: "Canguro", pista: "Boxeador" },
    { palabra: "Camello", pista: "Oasis" },
    { palabra: "Cocodrilo", pista: "Lacoste" },
    { palabra: "Iguana", pista: "Godzilla bebé" },
    { palabra: "Caracol", pista: "Casa propia" },
    { palabra: "Medusa", pista: "Inmortal" },
    { palabra: "Estrella de mar", pista: "Patricio" },
    { palabra: "Erizo", pista: "Sonic" },
    { palabra: "Castor", pista: "Ingeniero" },
    { palabra: "Nutria", pista: "Piedra pecho" },
    { palabra: "Foca", pista: "Aplauso" },
    { palabra: "Morsa", pista: "Beatles" },
    { palabra: "Leopardo", pista: "Tarzan" },
    { palabra: "Pantera", pista: "Rosa" },
    { palabra: "Tigre", pista: "Frosted Flakes" },
    { palabra: "Pavo real", pista: "Vanidad" },
    { palabra: "Flamenco", pista: "Una pata" },
    { palabra: "Loro", pista: "Pirata" },
    { palabra: "Tucán", pista: "Froot Loops" },
    { palabra: "Avestruz", pista: "Cabeza arena" },
    { palabra: "Cisne", pista: "Lago" },
    { palabra: "Pelícano", pista: "Buscando a Nemo" },
    { palabra: "Cuervo", pista: "Edgar Allan Poe" },
    { palabra: "Gaviota", pista: "Playa" },
    { palabra: "Paloma", pista: "Paz" },
    { palabra: "Golondrina", pista: "Primavera" },
    { palabra: "Colibrí", pista: "Vuelo estático" },
    { palabra: "Pato", pista: "Donald" },
    { palabra: "Ganso", pista: "Juego indie" },
    { palabra: "Gallina", pista: "Huevo" },
    { palabra: "Gallo", pista: "Despertador" },
    { palabra: "Pavo", pista: "Thanksgiving" },
    { palabra: "Codorniz", pista: "Huevos pequeños" },
    { palabra: "Halcón", pista: "Milenario" },
    { palabra: "Buitre", pista: "Carroñero" },
    { palabra: "Lechuza", pista: "Harry Potter" },
    { palabra: "Salamandra", pista: "Fuego" },
    { palabra: "Lagarto", pista: "Cola" },
    { palabra: "Camaleón", pista: "Cambio color" },
    { palabra: "Gecko", pista: "Pared" },
    { palabra: "Dragón de Komodo", pista: "Indonesia" },
    { palabra: "Anaconda", pista: "Jennifer Lopez" },
    { palabra: "Cobra", pista: "Kai" },
    { palabra: "Víbora", pista: "Veneno" },
    { palabra: "Pitón", pista: "Programación" },
    { palabra: "Caimán", pista: "Florida" },
    { palabra: "Piraña", pista: "Amazonas" },
    { palabra: "Pez espada", pista: "Nariz" },
    { palabra: "Manta raya", pista: "Steve Irwin" },
    { palabra: "Caballito de mar", pista: "Padre embarazado" },
    { palabra: "Anguila", pista: "Eléctrica" },
    { palabra: "Salmón", pista: "Contracorriente" },
    { palabra: "Atún", pista: "Lata" },
    { palabra: "Sardina", pista: "Apretados" },
    { palabra: "Bacalao", pista: "Noruega" },
    { palabra: "Trucha", pista: "Río" },
    { palabra: "Langosta", pista: "Friends" },
    { palabra: "Gamba", pista: "Forrest Gump" },
    { palabra: "Calamar", pista: "Tinta" },
    { palabra: "Almeja", pista: "Perla" },
    { palabra: "Mejillón", pista: "Galicia" },
    { palabra: "Ostra", pista: "Afrodisíaco" },
    { palabra: "Escarabajo", pista: "Egipto" },
    { palabra: "Mariquita", pista: "Siete puntos" },
  ],
  Películas: [
    { palabra: "Star Wars", pista: "Padre" },
    { palabra: "Harry Potter", pista: "Cicatriz" },
    { palabra: "Titanic", pista: "Puerta flotante" },
    { palabra: "Avatar", pista: "Unobtanium" },
    { palabra: "Matrix", pista: "Cuchara" },
    { palabra: "Jurassic Park", pista: "Vaso de agua" },
    { palabra: "El Rey León", pista: "Hakuna Matata" },
    { palabra: "Frozen", pista: "Suéltalo" },
    { palabra: "Toy Story", pista: "Infinito y más allá" },
    { palabra: "Shrek", pista: "Capas" },
    { palabra: "Piratas del Caribe", pista: "Ron" },
    { palabra: "Batman", pista: "Padres muertos" },
    { palabra: "Superman", pista: "Kryptonita" },
    { palabra: "Spider-Man", pista: "Tío Ben" },
    { palabra: "Iron Man", pista: "Cueva" },
    { palabra: "Avengers", pista: "Chasquido" },
    { palabra: "Indiana Jones", pista: "Serpientes" },
    { palabra: "E.T.", pista: "Teléfono casa" },
    { palabra: "Tiburón", pista: "Bote pequeño" },
    { palabra: "Terminator", pista: "Volveré" },
    { palabra: "Rocky", pista: "Adrian" },
    { palabra: "Forrest Gump", pista: "Caja de bombones" },
    { palabra: "El Padrino", pista: "Oferta" },
    { palabra: "Gladiador", pista: "Entretenidos" },
    { palabra: "Braveheart", pista: "Libertad" },
    { palabra: "Coco", pista: "Recuérdame" },
    { palabra: "Up", pista: "Squirrel" },
    { palabra: "Wall-E", pista: "Eva" },
    { palabra: "Buscando a Nemo", pista: "P. Sherman" },
    { palabra: "Monstruos S.A.", pista: "Risas" },
    { palabra: "Los Increíbles", pista: "Sin capas" },
    { palabra: "Ratatouille", pista: "Cualquiera puede cocinar" },
    { palabra: "Cars", pista: "Ka-chow" },
    { palabra: "Enredados", pista: "70 pies" },
    { palabra: "Moana", pista: "Te fiti" },
    { palabra: "Encanto", pista: "Bruno" },
    { palabra: "Kung Fu Panda", pista: "Secreto" },
    { palabra: "Madagascar", pista: "Me gustan mover" },
    { palabra: "Mi Villano Favorito", pista: "Banana" },
    { palabra: "Intensamente", pista: "Bing Bong" },
    { palabra: "Zootopia", pista: "Zanahoria" },
    { palabra: "Soul", pista: "Chispa" },
    { palabra: "Luca", pista: "Silencio Bruno" },
    { palabra: "El Señor de los Anillos", pista: "Precioso" },
    { palabra: "Hobbit", pista: "Segundo desayuno" },
    { palabra: "Narnia", pista: "Turkish delight" },
    { palabra: "Crepúsculo", pista: "Brilla" },
    { palabra: "Transformers", pista: "Más de lo que ves" },
    { palabra: "Misión Imposible", pista: "Mensaje destruido" },
    { palabra: "Fast and Furious", pista: "Familia" },
    { palabra: "John Wick", pista: "Lápiz" },
    { palabra: "Joker", pista: "Sociedad" },
    { palabra: "La La Land", pista: "Tráfico" },
    { palabra: "Bohemian Rhapsody", pista: "Mama" },
    { palabra: "Grease", pista: "Sandra Dee" },
    { palabra: "Jumanji", pista: "Dados" },
    { palabra: "Regreso al Futuro", pista: "DeLorean" },
    { palabra: "Ghostbusters", pista: "A quién llamar" },
    { palabra: "Men in Black", pista: "Flashy thing" },
    { palabra: "El Exorcista", pista: "Cabeza gira" },
    { palabra: "El Resplandor", pista: "Aquí está Johnny" },
    { palabra: "Psicosis", pista: "Ducha" },
    { palabra: "Alien", pista: "Espacio oír gritar" },
    { palabra: "Predator", pista: "Helicóptero" },
    { palabra: "Die Hard", pista: "Navidad" },
    { palabra: "Rambo", pista: "Bandana" },
    { palabra: "Top Gun", pista: "Maverick" },
    { palabra: "Dirty Dancing", pista: "Nadie rincón" },
    { palabra: "Ghost", pista: "Cerámica" },
    { palabra: "Pretty Woman", pista: "Gran error" },
    { palabra: "Notting Hill", pista: "Solo chica" },
    { palabra: "El Diario de Bridget Jones", pista: "Bragas grandes" },
    { palabra: "El Diablo viste de Prada", pista: "Eso es todo" },
    { palabra: "Breakfast Club", pista: "Detención" },
    { palabra: "Ferris Bueller", pista: "Día libre" },
    { palabra: "Karate Kid", pista: "Encerar" },
    { palabra: "School of Rock", pista: "Stick it to man" },
    { palabra: "Elf", pista: "Sonreír" },
    { palabra: "Home Alone", pista: "Kevin" },
    { palabra: "Grinch", pista: "Corazón pequeño" },
    { palabra: "Nightmare Before Christmas", pista: "Jack" },
    { palabra: "Beetlejuice", pista: "Tres veces" },
    { palabra: "Edward Scissorhands", pista: "Manos tijeras" },
    { palabra: "Charlie y la Fábrica de Chocolate", pista: "Ticket dorado" },
    { palabra: "Alicia en el País de las Maravillas", pista: "Conejo tarde" },
    { palabra: "Peter Pan", pista: "Segunda estrella" },
    { palabra: "La Cenicienta", pista: "Zapato cristal" },
    { palabra: "La Bella Durmiente", pista: "Huso" },
    { palabra: "La Sirenita", pista: "Bajo el mar" },
    { palabra: "Blancanieves", pista: "Manzana" },
    { palabra: "Aladdin", pista: "Tres deseos" },
    { palabra: "Mulán", pista: "Reflejo" },
    { palabra: "Pocahontas", pista: "Colores del viento" },
    { palabra: "Hércules", pista: "Cero a héroe" },
    { palabra: "Tarzán", pista: "Phil Collins" },
    { palabra: "Atlantis", pista: "Ciudad perdida" },
    { palabra: "Lilo y Stitch", pista: "Ohana" },
    { palabra: "Megamind", pista: "Presentación" },
    { palabra: "Cómo entrenar a tu dragón", pista: "Chimuelo" },
    { palabra: "El Gato con Botas", pista: "Ojos tiernos" },
  ],
  Objetos: [
    { palabra: "Teléfono", pista: "Notification" },
    { palabra: "Reloj", pista: "Dali" },
    { palabra: "Silla", pista: "Musical" },
    { palabra: "Lámpara", pista: "Genio" },
    { palabra: "Espejo", pista: "Madrastra" },
    { palabra: "Llave", pista: "Debajo felpudo" },
    { palabra: "Mesa", pista: "Negociación" },
    { palabra: "Libro", pista: "Cubierta" },
    { palabra: "Gafas", pista: "Clark Kent" },
    { palabra: "Paraguas", pista: "Mary Poppins" },
    { palabra: "Maleta", pista: "Perdida" },
    { palabra: "Cartera", pista: "Pulp Fiction" },
    { palabra: "Bolígrafo", pista: "Espada" },
    { palabra: "Tijeras", pista: "Piedra papel" },
    { palabra: "Cuchillo", pista: "Mantequilla" },
    { palabra: "Tenedor", pista: "Camino" },
    { palabra: "Cuchara", pista: "Matrix" },
    { palabra: "Plato", pista: "Volador" },
    { palabra: "Vaso", pista: "Medio lleno" },
    { palabra: "Taza", pista: "Padre" },
    { palabra: "Botella", pista: "Mensaje" },
    { palabra: "Nevera", pista: "Puerta abierta" },
    { palabra: "Microondas", pista: "Palomitas" },
    { palabra: "Lavadora", pista: "Calcetín perdido" },
    { palabra: "Televisión", pista: "Familia reunida" },
    { palabra: "Radio", pista: "Gaga" },
    { palabra: "Ventilador", pista: "Papel volando" },
    { palabra: "Aire acondicionado", pista: "Pelea oficina" },
    { palabra: "Estufa", pista: "No tocar" },
    { palabra: "Horno", pista: "Precalentar" },
    { palabra: "Sartén", pista: "Rapunzel" },
    { palabra: "Olla", pista: "Presión" },
    { palabra: "Cama", pista: "Despertador enemigo" },
    { palabra: "Almohada", pista: "Pelea" },
    { palabra: "Manta", pista: "Monstruo pies" },
    { palabra: "Sofá", pista: "Monedas" },
    { palabra: "Cortina", pista: "Ducha" },
    { palabra: "Alfombra", pista: "Aladdin" },
    { palabra: "Cuadro", pista: "Torcido" },
    { palabra: "Florero", pista: "Funeral" },
    { palabra: "Vela", pista: "Deseo" },
    { palabra: "Encendedor", pista: "Zippo" },
    { palabra: "Cerillas", pista: "Primera cita" },
    { palabra: "Linterna", pista: "Sombras chinescas" },
    { palabra: "Brújula", pista: "Norte moral" },
    { palabra: "Mapa", pista: "X marca" },
    { palabra: "Calendario", pista: "Tachar días" },
    { palabra: "Despertador", pista: "Snooze" },
    { palabra: "Calculadora", pista: "5318008" },
    { palabra: "Impresora", pista: "Sin tinta" },
    { palabra: "Escáner", pista: "Trasero" },
    { palabra: "Auriculares", pista: "Ignorar mundo" },
    { palabra: "Micrófono", pista: "Karaoke" },
    { palabra: "Cámara", pista: "Di patata" },
    { palabra: "Trípode", pista: "Selfie grupal" },
    { palabra: "Guitarra", pista: "Fogata" },
    { palabra: "Piano", pista: "88 teclas" },
    { palabra: "Batería", pista: "Vecinos" },
    { palabra: "Violín", pista: "Titanic" },
    { palabra: "Flauta", pista: "Colegio" },
    { palabra: "Trompeta", pista: "Louis Armstrong" },
    { palabra: "Saxofón", pista: "Jazz" },
    { palabra: "Acordeón", pista: "Polka" },
    { palabra: "Armónica", pista: "Blues" },
    { palabra: "Pandereta", pista: "Navidad" },
    { palabra: "Globo", pista: "Helio" },
    { palabra: "Dado", pista: "Suerte" },
    { palabra: "Naipes", pista: "Póker" },
    { palabra: "Ajedrez", pista: "Gambito" },
    { palabra: "Dominó", pista: "Efecto" },
    { palabra: "Puzle", pista: "Pieza perdida" },
    { palabra: "Peluche", pista: "Osito" },
    { palabra: "Muñeca", pista: "Barbie" },
    { palabra: "Patinete", pista: "Eléctrico" },
    { palabra: "Bicicleta", pista: "Cadena" },
    { palabra: "Monopatín", pista: "Tony Hawk" },
    { palabra: "Balón", pista: "Wilson" },
    { palabra: "Raqueta", pista: "Tenis" },
    { palabra: "Guante", pista: "Béisbol" },
    { palabra: "Casco", pista: "Moto" },
    { palabra: "Gorra", pista: "Béisbol" },
    { palabra: "Sombrero", pista: "Mago" },
    { palabra: "Bufanda", pista: "Invierno" },
    { palabra: "Guantes", pista: "Boxeo" },
    { palabra: "Cinturón", pista: "Batman" },
    { palabra: "Corbata", pista: "Oficina" },
    { palabra: "Anillo", pista: "Compromiso" },
    { palabra: "Collar", pista: "Perlas" },
    { palabra: "Pulsera", pista: "Amistad" },
    { palabra: "Pendientes", pista: "Orejas" },
    { palabra: "Mochila", pista: "Dora" },
    { palabra: "Bolso", pista: "Mary Poppins" },
    { palabra: "Billetera", pista: "Pulp Fiction" },
    { palabra: "Pasaporte", pista: "Viaje" },
    { palabra: "Ticket", pista: "Concierto" },
    { palabra: "Periódico", pista: "Ayer" },
    { palabra: "Revista", pista: "Peluquería" },
    { palabra: "Sobre", pista: "Carta" },
    { palabra: "Sello", pista: "Correos" },
    { palabra: "Moneda", pista: "Fuente" },
  ],
  Deportes: [
    { palabra: "Fútbol", pista: "Mano de Dios" },
    { palabra: "Tenis", pista: "Love" },
    { palabra: "Natación", pista: "Phelps" },
    { palabra: "Baloncesto", pista: "Slam dunk" },
    { palabra: "Ciclismo", pista: "Tour amarillo" },
    { palabra: "Boxeo", pista: "Float like butterfly" },
    { palabra: "Golf", pista: "Fore" },
    { palabra: "Hockey", pista: "Sobre hielo" },
    { palabra: "Rugby", pista: "Scrum" },
    { palabra: "Voleibol", pista: "Wilson" },
    { palabra: "Béisbol", pista: "Home run" },
    { palabra: "Atletismo", pista: "Bolt" },
    { palabra: "Gimnasia", pista: "Diez perfecto" },
    { palabra: "Esgrima", pista: "Mosqueteros" },
    { palabra: "Judo", pista: "Cinturón" },
    { palabra: "Karate", pista: "Miyagi" },
    { palabra: "Taekwondo", pista: "Korea" },
    { palabra: "Surf", pista: "Gnarly" },
    { palabra: "Esquí", pista: "Après" },
    { palabra: "Snowboard", pista: "Half pipe" },
    { palabra: "Patinaje", pista: "Triple axel" },
    { palabra: "Escalada", pista: "Free solo" },
    { palabra: "Remo", pista: "Oxford Cambridge" },
    { palabra: "Vela", pista: "Copa América" },
    { palabra: "Waterpolo", pista: "Submarino" },
    { palabra: "Polo", pista: "Príncipe" },
    { palabra: "Críquet", pista: "Tea time" },
    { palabra: "Bádminton", pista: "Pluma" },
    { palabra: "Ping Pong", pista: "Forest Gump" },
    { palabra: "Billar", pista: "Color solido" },
    { palabra: "Dardos", pista: "Pub" },
    { palabra: "Bolos", pista: "Strike" },
    { palabra: "Ajedrez", pista: "Gambito" },
    { palabra: "Tiro con arco", pista: "Katniss" },
    { palabra: "Halterofilia", pista: "Barra olímpica" },
    { palabra: "Lucha libre", pista: "WWE" },
    { palabra: "Triatlón", pista: "Ironman" },
    { palabra: "Maratón", pista: "42.195" },
    { palabra: "Salto de altura", pista: "Fosbury" },
    { palabra: "Salto de longitud", pista: "Carl Lewis" },
    { palabra: "Lanzamiento de peso", pista: "Rotación" },
    { palabra: "Lanzamiento de jabalina", pista: "Grecia antigua" },
    { palabra: "Decatlón", pista: "Rey atletas" },
    { palabra: "Pentatlón", pista: "Moderno" },
    { palabra: "Motociclismo", pista: "Rossi" },
    { palabra: "Fórmula 1", pista: "Pit stop" },
    { palabra: "Rally", pista: "Derrapar" },
    { palabra: "Karting", pista: "Mario" },
    { palabra: "Skate", pista: "Tony Hawk" },
    { palabra: "BMX", pista: "E.T." },
    { palabra: "Parkour", pista: "Yamakasi" },
    { palabra: "CrossFit", pista: "WOD" },
    { palabra: "Yoga", pista: "Namaste" },
    { palabra: "Pilates", pista: "Core" },
    { palabra: "Zumba", pista: "Fiesta" },
    { palabra: "Buceo", pista: "Nemo" },
    { palabra: "Snorkel", pista: "Tubo" },
    { palabra: "Kayak", pista: "Río rápido" },
    { palabra: "Canoa", pista: "Pocahontas" },
    { palabra: "Paddle Surf", pista: "De pie" },
    { palabra: "Windsurf", pista: "Viento tabla" },
    { palabra: "Kitesurf", pista: "Cometa" },
    { palabra: "Wakeboard", pista: "Lancha" },
    { palabra: "Esquí acuático", pista: "Dos tablas" },
    { palabra: "Rafting", pista: "Rápidos" },
    { palabra: "Paracaidismo", pista: "Geronimo" },
    { palabra: "Parapente", pista: "Montaña" },
    { palabra: "Ala delta", pista: "Batman" },
    { palabra: "Puenting", pista: "Bungee" },
    { palabra: "Tirolina", pista: "Zip line" },
    { palabra: "Rappel", pista: "Descender" },
    { palabra: "Montañismo", pista: "Everest" },
    { palabra: "Senderismo", pista: "Camino" },
    { palabra: "Trail running", pista: "Montaña corriendo" },
    { palabra: "Orientación", pista: "Brújula" },
    { palabra: "Geocaching", pista: "GPS tesoro" },
    { palabra: "Paintball", pista: "Mancha" },
    { palabra: "Airsoft", pista: "Réplica" },
    { palabra: "Tiro olímpico", pista: "Diana" },
    { palabra: "Esgrima", pista: "Florete" },
    { palabra: "Kickboxing", pista: "Patada puño" },
    { palabra: "Muay Thai", pista: "Codos rodillas" },
    { palabra: "MMA", pista: "Jaula" },
    { palabra: "Sumo", pista: "Japón pesado" },
    { palabra: "Kung Fu", pista: "Shaolin" },
    { palabra: "Aikido", pista: "Defensa" },
    { palabra: "Capoeira", pista: "Brasil danza" },
    { palabra: "Curling", pista: "Escoba hielo" },
    { palabra: "Bobsled", pista: "Jamaica" },
    { palabra: "Luge", pista: "Trineo" },
    { palabra: "Skeleton", pista: "Cabeza primero" },
    { palabra: "Hockey hierba", pista: "Césped" },
    { palabra: "Lacrosse", pista: "Red palo" },
    { palabra: "Frontenis", pista: "Pelota vasca" },
    { palabra: "Squash", pista: "Cuatro paredes" },
    { palabra: "Pádel", pista: "España moda" },
    { palabra: "Petanca", pista: "Francia bolas" },
    { palabra: "Croquet", pista: "Alicia" },
    { palabra: "Polo acuático", pista: "Piscina caballo" },
    { palabra: "Salto trampolín", pista: "Clavados" },
  ],
  Comida: [
    { palabra: "Pizza", pista: "Ninja Turtles" },
    { palabra: "Hamburguesa", pista: "Big Mac" },
    { palabra: "Sushi", pista: "Wasabi" },
    { palabra: "Helado", pista: "Brain freeze" },
    { palabra: "Pasta", pista: "Al dente" },
    { palabra: "Tacos", pista: "Martes" },
    { palabra: "Paella", pista: "Valenciana" },
    { palabra: "Tortilla", pista: "Con o sin" },
    { palabra: "Gazpacho", pista: "Venganza" },
    { palabra: "Croquetas", pista: "Abuela" },
    { palabra: "Empanada", pista: "Gallega" },
    { palabra: "Churros", pista: "San Ginés" },
    { palabra: "Flan", pista: "Agujeros" },
    { palabra: "Natillas", pista: "Galleta encima" },
    { palabra: "Tarta", pista: "Mentira" },
    { palabra: "Galletas", pista: "Santa" },
    { palabra: "Magdalenas", pista: "Proust" },
    { palabra: "Donuts", pista: "Homer" },
    { palabra: "Croissant", pista: "Media luna" },
    { palabra: "Pan", pista: "Sliced" },
    { palabra: "Bocadillo", pista: "Recreo" },
    { palabra: "Sandwich", pista: "Conde" },
    { palabra: "Ensalada", pista: "César" },
    { palabra: "Sopa", pista: "Letras" },
    { palabra: "Caldo", pista: "Resfriado" },
    { palabra: "Arroz", pista: "Boda" },
    { palabra: "Lentejas", pista: "Viernes" },
    { palabra: "Garbanzos", pista: "Hummus" },
    { palabra: "Judías", pista: "Mágicas" },
    { palabra: "Guisantes", pista: "Princesa" },
    { palabra: "Patatas fritas", pista: "Ketchup o mayo" },
    { palabra: "Puré", pista: "Bebé" },
    { palabra: "Filete", pista: "Punto" },
    { palabra: "Pollo asado", pista: "Domingo" },
    { palabra: "Pescado", pista: "Espina" },
    { palabra: "Marisco", pista: "Alergia" },
    { palabra: "Jamón", pista: "5J" },
    { palabra: "Chorizo", pista: "Español" },
    { palabra: "Salchichas", pista: "Frankfurt" },
    { palabra: "Bacon", pista: "Everything better" },
    { palabra: "Huevos fritos", pista: "Punky" },
    { palabra: "Tortilla francesa", pista: "Hotel" },
    { palabra: "Revuelto", pista: "Ajetes" },
    { palabra: "Queso", pista: "Say cheese" },
    { palabra: "Yogur", pista: "Probiótico" },
    { palabra: "Leche", pista: "Got milk" },
    { palabra: "Mantequilla", pista: "Paula" },
    { palabra: "Mermelada", pista: "Abuela" },
    { palabra: "Miel", pista: "Luna de" },
    { palabra: "Chocolate", pista: "Wonka" },
    { palabra: "Caramelos", pista: "Dentista" },
    { palabra: "Chicle", pista: "Debajo mesa" },
    { palabra: "Palomitas", pista: "Cine" },
    { palabra: "Nachos", pista: "Estadio" },
    { palabra: "Guacamole", pista: "Extra" },
    { palabra: "Burrito", pista: "Enrollado" },
    { palabra: "Quesadilla", pista: "México queso" },
    { palabra: "Enchiladas", pista: "Salsa roja" },
    { palabra: "Fajitas", pista: "Sizzling" },
    { palabra: "Ceviche", pista: "Perú" },
    { palabra: "Ramen", pista: "Naruto" },
    { palabra: "Dim Sum", pista: "Hong Kong" },
    { palabra: "Curry", pista: "India" },
    { palabra: "Pad Thai", pista: "Tailandia" },
    { palabra: "Kebab", pista: "Döner" },
    { palabra: "Falafel", pista: "Garbanzo frito" },
    { palabra: "Hummus", pista: "Chickpea dip" },
    { palabra: "Gyros", pista: "Grecia" },
    { palabra: "Moussaka", pista: "Berenjena griega" },
    { palabra: "Lasaña", pista: "Garfield" },
    { palabra: "Risotto", pista: "Italia cremoso" },
    { palabra: "Gnocchi", pista: "Patata pasta" },
    { palabra: "Ravioli", pista: "Relleno" },
    { palabra: "Canelones", pista: "Navidad" },
    { palabra: "Macarrones", pista: "Con queso" },
    { palabra: "Espaguetis", pista: "Dama vagabundo" },
    { palabra: "Carbonara", pista: "Huevo bacon" },
    { palabra: "Bolognesa", pista: "Carne picada" },
    { palabra: "Pesto", pista: "Albahaca" },
    { palabra: "Bruschetta", pista: "Tomate pan" },
    { palabra: "Carpaccio", pista: "Crudo" },
    { palabra: "Tiramisú", pista: "Café postre" },
    { palabra: "Panna cotta", pista: "Cremoso italiano" },
    { palabra: "Gelato", pista: "Helado italiano" },
    { palabra: "Croissant", pista: "Francia desayuno" },
    { palabra: "Baguette", pista: "Pan largo" },
    { palabra: "Crêpe", pista: "Nutella" },
    { palabra: "Macarons", pista: "Colores pastel" },
    { palabra: "Éclair", pista: "Chocolate alargado" },
    { palabra: "Profiteroles", pista: "Bolitas" },
    { palabra: "Brioche", pista: "María Antonieta" },
    { palabra: "Quiche", pista: "Tarta salada" },
    { palabra: "Fondue", pista: "Suiza queso" },
    { palabra: "Raclette", pista: "Derretir queso" },
    { palabra: "Pretzel", pista: "Alemania" },
    { palabra: "Bratwurst", pista: "Salchicha alemana" },
    { palabra: "Schnitzel", pista: "Empanado" },
    { palabra: "Fish and chips", pista: "Inglaterra" },
    { palabra: "Haggis", pista: "Escocia" },
    { palabra: "Pierogi", pista: "Polonia" },
  ],
  Tecnología: [
    { palabra: "Ordenador", pista: "2001 HAL" },
    { palabra: "Internet", pista: "Gato videos" },
    { palabra: "Robot", pista: "Asimov" },
    { palabra: "Videojuego", pista: "Respawn" },
    { palabra: "Cámara", pista: "Sonríe" },
    { palabra: "Drone", pista: "Ojo cielo" },
    { palabra: "Tablet", pista: "Entre" },
    { palabra: "Smartphone", pista: "Crack pantalla" },
    { palabra: "Smartwatch", pista: "Pasos" },
    { palabra: "Auriculares", pista: "Antisocial" },
    { palabra: "Altavoz", pista: "Alexa" },
    { palabra: "Televisor", pista: "Netflix" },
    { palabra: "Proyector", pista: "Presentación" },
    { palabra: "Consola", pista: "Red ring" },
    { palabra: "Teclado", pista: "QWERTY" },
    { palabra: "Ratón", pista: "Scroll infinito" },
    { palabra: "Monitor", pista: "Dual" },
    { palabra: "Disco duro", pista: "Lleno" },
    { palabra: "USB", pista: "Tercer intento" },
    { palabra: "Tarjeta SD", pista: "Cámara antigua" },
    { palabra: "Batería", pista: "1% ansiedad" },
    { palabra: "Cargador", pista: "Olvidado hotel" },
    { palabra: "Cable", pista: "Nudo" },
    { palabra: "Wifi", pista: "Contraseña nevera" },
    { palabra: "Bluetooth", pista: "Rey vikingo" },
    { palabra: "GPS", pista: "Recalculando" },
    { palabra: "Impresora 3D", pista: "Capa por capa" },
    { palabra: "Escáner", pista: "Oficina 90s" },
    { palabra: "Webcam", pista: "Tapar cámara" },
    { palabra: "Micrófono", pista: "Muteado" },
    { palabra: "Realidad virtual", pista: "Mareo" },
    { palabra: "Inteligencia artificial", pista: "Skynet" },
    { palabra: "Blockchain", pista: "Descentralizado" },
    { palabra: "Criptomoneda", pista: "HODL" },
    { palabra: "Servidor", pista: "Caído" },
    { palabra: "Nube", pista: "No mi ordenador" },
    { palabra: "Base de datos", pista: "SQL" },
    { palabra: "Código", pista: "Bug" },
    { palabra: "Aplicación", pista: "Hay una para eso" },
    { palabra: "Sistema operativo", pista: "Reiniciar" },
    { palabra: "Antivirus", pista: "Norton" },
    { palabra: "Firewall", pista: "Bloqueado" },
    { palabra: "Hacker", pista: "Hoodie" },
    { palabra: "Encriptación", pista: "Enigma" },
    { palabra: "Red social", pista: "Scroll infinito" },
    { palabra: "Streaming", pista: "Buffering" },
    { palabra: "Podcast", pista: "Auriculares trabajo" },
    { palabra: "Blog", pista: "2005" },
    { palabra: "Email", pista: "You got mail" },
    { palabra: "Buscador", pista: "Página 2" },
    { palabra: "Navegador", pista: "Demasiadas pestañas" },
    { palabra: "Dominio", pista: ".com" },
    { palabra: "Hosting", pista: "Uptime" },
    { palabra: "API", pista: "Conexión" },
    { palabra: "Plugin", pista: "Actualizar" },
    { palabra: "Algoritmo", pista: "Recomendaciones" },
    { palabra: "Píxel", pista: "Pantalla pequeño" },
    { palabra: "Resolución", pista: "4K" },
    { palabra: "Memoria RAM", pista: "Chrome come" },
    { palabra: "Procesador", pista: "Intel inside" },
    { palabra: "Tarjeta gráfica", pista: "Gaming" },
    { palabra: "SSD", pista: "Rápido silencioso" },
    { palabra: "Router", pista: "Parpadea luces" },
    { palabra: "Módem", pista: "Dial up" },
    { palabra: "Ethernet", pista: "Cable azul" },
    { palabra: "Fibra óptica", pista: "Luz velocidad" },
    { palabra: "5G", pista: "Conspiración" },
    { palabra: "Satélite", pista: "Órbita" },
    { palabra: "Código QR", pista: "Escanear menú" },
    { palabra: "NFC", pista: "Pago móvil" },
    { palabra: "Biometría", pista: "Huella dactilar" },
    { palabra: "Reconocimiento facial", pista: "Desbloquear" },
    { palabra: "Chatbot", pista: "Atención cliente" },
    { palabra: "Machine learning", pista: "Aprender datos" },
    { palabra: "Big data", pista: "Mucha información" },
    { palabra: "Metaverso", pista: "Zuckerberg" },
    { palabra: "NFT", pista: "Mono aburrido" },
    { palabra: "Ciberseguridad", pista: "Protección" },
    { palabra: "Phishing", pista: "Email falso" },
    { palabra: "Ransomware", pista: "Secuestro datos" },
    { palabra: "VPN", pista: "Privacidad" },
    { palabra: "Proxy", pista: "Intermediario" },
    { palabra: "Dark web", pista: "Onion" },
    { palabra: "Bitcoin", pista: "Satoshi" },
    { palabra: "Ethereum", pista: "Smart contracts" },
    { palabra: "Token", pista: "Digital" },
    { palabra: "Wallet", pista: "Billetera cripto" },
    { palabra: "Mining", pista: "Minar" },
    { palabra: "Debugging", pista: "Arreglar errores" },
    { palabra: "Compilador", pista: "Código máquina" },
    { palabra: "Framework", pista: "Estructura" },
    { palabra: "Librería", pista: "Código reutilizable" },
    { palabra: "GitHub", pista: "Gato pulpo" },
    { palabra: "Stack Overflow", pista: "Copiar pegar" },
    { palabra: "Terminal", pista: "Pantalla negra" },
    { palabra: "Linux", pista: "Pingüino" },
    { palabra: "Windows", pista: "Pantalla azul" },
    { palabra: "MacOS", pista: "Manzana" },
    { palabra: "Android", pista: "Robot verde" },
    { palabra: "iOS", pista: "Manzana móvil" },
  ],
  General: [
    { palabra: "Escuela", pista: "Timbre" },
    { palabra: "Hospital", pista: "Bata abierta" },
    { palabra: "Playa", pista: "Arena zapatos" },
    { palabra: "Navidad", pista: "Cuñados" },
    { palabra: "Cumpleaños", pista: "Soplar" },
    { palabra: "Circo", pista: "Payaso triste" },
    { palabra: "Museo", pista: "No tocar" },
    { palabra: "Biblioteca", pista: "Shhhh" },
    { palabra: "Cine", pista: "Palomitas caras" },
    { palabra: "Teatro", pista: "Merde" },
    { palabra: "Concierto", pista: "Encendedor" },
    { palabra: "Parque", pista: "Palomas" },
    { palabra: "Zoo", pista: "Olor" },
    { palabra: "Acuario", pista: "Nemo" },
    { palabra: "Aeropuerto", pista: "Líquidos 100ml" },
    { palabra: "Estación", pista: "Vía 9 3/4" },
    { palabra: "Puerto", pista: "Gaviotas" },
    { palabra: "Hotel", pista: "Minibar" },
    { palabra: "Restaurante", pista: "Propina" },
    { palabra: "Supermercado", pista: "Caja rápida" },
    { palabra: "Farmacia", pista: "Cruz verde" },
    { palabra: "Banco", pista: "Cola" },
    { palabra: "Oficina", pista: "Lunes" },
    { palabra: "Fábrica", pista: "Turnos" },
    { palabra: "Granja", pista: "Madrugón" },
    { palabra: "Castillo", pista: "Fantasma" },
    { palabra: "Iglesia", pista: "Domingo" },
    { palabra: "Mezquita", pista: "Descalzo" },
    { palabra: "Templo", pista: "Incienso" },
    { palabra: "Cementerio", pista: "Flores" },
    { palabra: "Boda", pista: "Ramo" },
    { palabra: "Funeral", pista: "Negro" },
    { palabra: "Graduación", pista: "Birrete aire" },
    { palabra: "Entrevista", pista: "Sudor" },
    { palabra: "Vacaciones", pista: "Fuera oficina" },
    { palabra: "Camping", pista: "Mosquitos" },
    { palabra: "Montaña", pista: "Eco" },
    { palabra: "Bosque", pista: "Hansel Gretel" },
    { palabra: "Desierto", pista: "Espejismo" },
    { palabra: "Selva", pista: "Tarzán" },
    { palabra: "Río", pista: "Llorar" },
    { palabra: "Lago", pista: "Cisne" },
    { palabra: "Cascada", pista: "Barril" },
    { palabra: "Volcán", pista: "Pompeya" },
    { palabra: "Cueva", pista: "Platón" },
    { palabra: "Isla", pista: "Desierta" },
    { palabra: "Ciudad", pista: "Never sleeps" },
    { palabra: "Pueblo", pista: "Todos conocen" },
    { palabra: "Carretera", pista: "66" },
    { palabra: "Puente", pista: "Quemar" },
    { palabra: "Túnel", pista: "Luz al final" },
    { palabra: "Semáforo", pista: "Ámbar" },
    { palabra: "Paso de cebra", pista: "Abbey Road" },
    { palabra: "Gasolinera", pista: "Olor" },
    { palabra: "Taller", pista: "Presupuesto" },
    { palabra: "Gimnasio", pista: "Enero" },
    { palabra: "Piscina", pista: "Tirarse bomba" },
    { palabra: "Spa", pista: "Relax" },
    { palabra: "Sauna", pista: "Finlandia" },
    { palabra: "Peluquería", pista: "Revista vieja" },
    { palabra: "Barbería", pista: "Hipster" },
    { palabra: "Dentista", pista: "Dolor" },
    { palabra: "Médico", pista: "Espera" },
    { palabra: "Veterinario", pista: "Patitas" },
    { palabra: "Abogado", pista: "Objeción" },
    { palabra: "Policía", pista: "Sirena" },
    { palabra: "Bombero", pista: "Escalera" },
    { palabra: "Cartero", pista: "Perro persigue" },
    { palabra: "Chef", pista: "Gorro alto" },
    { palabra: "Camarero", pista: "Propina" },
    { palabra: "Piloto", pista: "Capitán habla" },
    { palabra: "Astronauta", pista: "Houston problema" },
    { palabra: "Científico", pista: "Bata blanca" },
    { palabra: "Profesor", pista: "Tiza" },
    { palabra: "Estudiante", pista: "Exámenes" },
    { palabra: "Artista", pista: "Boina" },
    { palabra: "Músico", pista: "Gira" },
    { palabra: "Actor", pista: "Oscar" },
    { palabra: "Director", pista: "Acción" },
    { palabra: "Escritor", pista: "Bloqueo" },
    { palabra: "Periodista", pista: "Scoop" },
    { palabra: "Fotógrafo", pista: "Sonríe" },
    { palabra: "Arquitecto", pista: "Planos" },
    { palabra: "Ingeniero", pista: "Calculadora" },
    { palabra: "Mecánico", pista: "Manos sucias" },
    { palabra: "Electricista", pista: "Calambre" },
    { palabra: "Fontanero", pista: "Mario" },
    { palabra: "Carpintero", pista: "Serrín" },
    { palabra: "Jardinero", pista: "Manguera" },
    { palabra: "Granjero", pista: "Tractor" },
    { palabra: "Pescador", pista: "Paciencia" },
    { palabra: "Cazador", pista: "Silencio" },
    { palabra: "Atleta", pista: "Medalla" },
    { palabra: "Entrenador", pista: "Silbato" },
    { palabra: "Árbitro", pista: "Tarjeta" },
    { palabra: "DJ", pista: "Mesa mezclas" },
    { palabra: "Influencer", pista: "Filtros" },
    { palabra: "Youtuber", pista: "Suscríbete" },
    { palabra: "Streamer", pista: "Donaciones" },
    { palabra: "Gamer", pista: "GG" },
  ],
};

export type GameMode = "classic" | "multiplayer";
export type PlayerRole = "impostor" | "civil";

export interface Player {
  id: string;
  name: string;
  role?: PlayerRole;
  word?: string;
  isAdmin?: boolean;
  color: string;
}

export interface ClueEntry {
  playerId: string;
  playerName: string;
  clue: string;
}

export interface Vote {
  voterId: string;
  voterName: string;
  votedForId: string;
}

export interface GameState {
  mode: GameMode;
  category: Category;
  impostorCount: number;
  players: Player[];
  currentTurnIndex: number;
  gamePhase: "setup" | "playing" | "clues" | "voting" | "results" | "finished";
  roomCode?: string;
  startingPlayer?: string;
  myPlayerData?: Player;
  clues?: ClueEntry[];
  votes?: Vote[];
  hasVoted?: boolean;
}

export const playerColors = [
  "#3B82F6", // blue
  "#10B981", // green
  "#8B5CF6", // purple
  "#F59E0B", // amber
  "#EC4899", // pink
  "#06B6D4", // cyan
  "#F97316", // orange
  "#84CC16", // lime
  "#6366F1", // indigo
  "#14B8A6", // teal
];

export const insertGameStateSchema = z.object({
  mode: z.enum(["classic", "multiplayer"]),
  category: z.enum(categories),
  impostorCount: z.number().min(1).max(5),
  playerCount: z.number().min(3).max(10).optional(),
});

export type InsertGameState = z.infer<typeof insertGameStateSchema>;

export interface RoomMessage {
  type: "join" | "leave" | "start" | "turn" | "next" | "error" | "roomState" | "gameStarted" | "turnUpdate";
  payload: unknown;
}

export interface JoinPayload {
  roomCode: string;
  playerName: string;
}

export interface RoomStatePayload {
  roomCode: string;
  players: Player[];
  category: Category;
  impostorCount: number;
  isAdmin: boolean;
}

export interface GameStartedPayload {
  player: Player;
  currentTurnIndex: number;
  totalPlayers: number;
  startingPlayer: string;
}

export interface TurnUpdatePayload {
  currentTurnIndex: number;
  currentPlayerName: string;
}

export const users = {
  id: "",
  username: "",
  password: "",
};

export const insertUserSchema = z.object({
  username: z.string(),
  password: z.string(),
});

export type InsertUser = z.infer<typeof insertUserSchema>;
export type User = typeof users;

export function getRandomWord(category: Category): WordPair {
  const words = categoryWords[category];
  const randomIndex = Math.floor(Math.random() * words.length);
  return words[randomIndex];
}
